### ISSUE TITLE
How to change attributes of checkbox.

### ISSUE THREAD

**Issue by elonmusk-01** [jorisschellekens/borb-examples#16]
Hi, @jorisschellekens Thank you for an amazing implementation. I am using checkboxes in my pdf but I expect different shapes of checkboxes and also different sizes. As its implementation is in to-do so I am unaware of attributes accepted by the checkbox class. How can I achieve this?

**Comment by elonmusk-01** [comment]
Also, I am not sure how to add some text with a checkbox in the same cell of a table.

**Comment by jorisschellekens** [comment]
Hi @elonmusk-01,

Thank you for your interest in borb.
I'm afraid checkboxes are one the items that will still require some work.

You can (if you really want to) look at the iso spec and attempt to implement it yourself. Or you can wait until I build a release which supports checkboxes more thoroughly. 

Kind regards,
Joris Schellekens
