### ISSUE TITLE
Trigger javascript on change of TextField value

### ISSUE THREAD

**Issue by hscheewel** [jorisschellekens/borb-examples#17]
Dear Joris,
Many thanks for creating such a great library for building PDF documents from Python! I really enjoy playing with it!
In one of the chapters, you provide an example in which a javascript function is called when pushing a button.
Would it be also possible to trigger a piece of script when exiting the edit mode of a text field / when the value of a field is changed?
Many thanks in advance for your answer!
Best,
Hendrik

**Comment by jorisschellekens** [comment]
Hi Hendrik,

In future please ask your question on StackOverflow. It has a tag `borb` wich I watch. Considering your question does not really address a bug, and isn't a feature request, I don't think it really belongs here. (I will answer it nonetheless.)

It is certainly possible to trigger javascript in a PDF based on the selection and de-selection of a TextField. There's a good forum (run by Adobe) which helps users out with javascript in PDF. But the definitive source (at least in terms of what Adobe supports) can be found [here](https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_jsapiref.pdf).

Keep in mind however that javascript in PDF is not supported by every reader, and not every supports the same subset. So you might need to check whether your PDF works in all readers you are targeting.

Kind regards,
Joris Schellekens

**Comment by hscheewel** [comment]
Hi Joris,
Thanks for your response and the contained information! I'll check out the pdf. 
And sorry for asking this question at the wrong place! I find feature requests always a bit rude and this is why I reformulated my usecase in a question. 
Best,
Hendrik

**Comment by hscheewel** [comment]
Dear Joris,
Sorry for commenting here again. Looking at the borb code for the pdf form elements, it seems to me that an implementation of a JavascriptTextField similar to the JavascriptPushButton would be feasible. Or do you see larger technical complications here? I'd like to give it a try ...

**Comment by jorisschellekens** [comment]
Hi,

This is a feature request, so I'm ok with you posting it here.

Some small remarks:
1. This is the examples repository. It would be better if you created an issue on the actual borb repository. Unless you specifically meant "please create an example".
2. What exactly do you expect JavascriptTextField to do?
3. There are probably a lot of events that pdf formfields can respond to. Whereas a pushbutton kinda only does one thing.
4. If you want to continue working on this issue, it would be better to reopen the issue.

Kind regards,
Joris Schellekens
