### ISSUE TITLE
Error: Paragraph object has no attribute layout

### ISSUE THREAD

**Issue by olexsyn** [jorisschellekens/borb-examples#20]
I am getting an error when running snippets

chapter_002/src/snippet_018.py
...
chapter_002/src/snippet_027.py

: 'Paragraph' object has no attribute 'layout'

For example:
chapter_002/src/snippet_022.py

crashed with error:

```
Traceback (most recent call last):
  File "/home/.../cgi-bin/test_borb_sn022.py", line 47, in <module>
    main()
  File "/home/.../cgi-bin/test_borb_sn022.py", line 39, in main
    ).layout(page, r)
AttributeError: 'Paragraph' object has no attribute 'layout'
```

Distributor ID:	Ubuntu
Description:	Linux Lite 6.0
Release:	22.04
Codename:	jammy

Python 3.10.4

borb-2.1.0
Pillow-9.2.0
certifi-2022.6.15.1
charset-normalizer-2.1.1
fonttools-4.37.1
idna-3.3
python-barcode-0.14.0
qrcode-7.3.1
requests-2.28.1
urllib3-1.26.12

**Comment by jorisschellekens** [comment]
Hi there,

I recently changed the entire `LayoutElement` framework. I didn't get around to changing all examples yet. It might take some time.

Kind regards,
Joris Schellekens
