### ISSUE TITLE
cannot import name 'Document' from 'borb.pdf'

### ISSUE THREAD

**Issue by nikogamulin** [jorisschellekens/borb-examples#21]
Hi, while trying to import the following, I got an error

```
from pathlib import Path

from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import SingleColumnLayout
from borb.pdf import Paragraph
from borb.pdf import PDF
```

ImportError: cannot import name 'Document' from 'borb.pdf' (/home/niko/anaconda3/envs/py39/lib/python3.9/site-packages/borb/pdf/__init__.py)

version: '2.1.5.2'

**Comment by jorisschellekens** [comment]
That's odd. Although I don't explicitly test anaconda.
Can you try pip?

**Comment by jorisschellekens** [comment]
Hi there,

I did not receive feedback from you in 7 days. I am therefor closing this issue.

Kind regards,
Joris Schellekens
