### ISSUE TITLE
snippet_013.py error?

### ISSUE THREAD

**Issue by dt215git** [jorisschellekens/borb-examples#22]
[chapter_005/src/snippet_013.py](https://github.com/jorisschellekens/borb-examples/blob/master/chapter_005/src/snippet_013.py) fails with the following error:
`
from borb.toolkit.color.color_spectrum_extraction import ColorSpectrumExtraction
ModuleNotFoundError: No module named 'borb.toolkit.color.color_spectrum_extraction'
`

[borb.toolkit.color](https://github.com/jorisschellekens/borb/blob/master/borb/toolkit/color/color_extraction.py) doesn't appear to contain a `color_spectrum_extraction` function.

Should these two references to **ColorSpectrumExtraction** in snippet_013.py be changed to **ColorExtraction**? Or is something else amiss?

```python
from borb.toolkit.color.color_spectrum_extraction import ColorSpectrumExtraction
... some code removed ...
l: ColorSpectrumExtraction = ColorSpectrumExtraction()
```

**Comment by jorisschellekens** [comment]
Hi,

It's hard sometimes to keep the documentation and code of borb in sync.
Recently I've entered into a partnership with educative.io. They will be publishing a course on how to use `borb`.
In light of this course, I have begun a thorough review of the documentation, and have made changes to the code.

For example, `ColorSpectrumExtraction` has become `ColorExtraction`.
There are a few minor name-changes here and there.

I do have a script to automatically run all the samples in the ebook/repository. That is already a big help.
I'll try to upload a new version of the docs today.

Kind regards,
Joris Schellekens
