### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Igr444** [jorisschellekens/borb-examples#27]
Hello!  great library.  thanks for your work.  Through the translator I studied the documentation, but did not find it. how to add header and footer to pages?

**Comment by jorisschellekens** [comment]
Hi there,

There's currently no example for adding headers or footers to a PDF, even though `borb` does support it.

You can check out this test, it should give you a good practical example.

https://github.com/jorisschellekens/borb/blob/master/tests/pdf/canvas/layout/page_layout/test_header_footer_multi_column_layout.py

Kind regards,
Joris Schellekens
