### ISSUE TITLE
Why I use SimpleTextExtraction extracting text but pages not right

### ISSUE THREAD

**Issue by Victor94-king** [jorisschellekens/borb-examples#30]
Dear all,

As I followed the instructions to extract text using the code below ,  but I found the order of variable(pages) is totally right comparing with my original pdf file , and I attached the code and pic below .

```
import typing
from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleTextExtraction
import os 
import numpy as np
import argparse
doc: typing.Optional[Document] = None
l: SimpleTextExtraction = SimpleTextExtraction()
with open('1.pdf', "rb") as in_file_handle:
    doc = PDF.loads(in_file_handle, [l])

assert doc is not None

pages = l.get_text()
pages
```

The pic below as u can see , pages[1] is the page of 4 for my pdf file , so it not matched . Could u plz tell me how to solve it , since in my pdf file there is no pages info writen in the pdf file.

![image](https://github.com/jorisschellekens/borb-examples/assets/103173758/96e9179e-d077-4c2e-9e32-e6f8da0bf4d7)

**Comment by jorisschellekens** [comment]
Please attach your input document. It is impossible for me to reproduce your bug otherwise.

**Comment by jorisschellekens** [comment]
It is impossible for me to reproduce your bug without your document. You've had a week to provide me with the document. I am closing this ticket.
