### ISSUE TITLE
How to select column manually in MultiColumnLayout page?

### ISSUE THREAD

**Issue by avi-chandra** [jorisschellekens/borb-examples#4]
I have created a MultiColumnLayout pdf page and adding table and graph in the page.

Is there any way I can add the graph in second column (manually) of page whether the first column is full or not?

**Comment by jorisschellekens** [comment]
Issues are meant for "this does not work" or "I have found a bug" or "this is a feature request".

Issues are **not** meant for problem solving. Please ask your question on Stackoverflow, like I already told you to do when you first posted it on Reddit.

Also, check out the documentation of the class before asking your question. 

You'll find the method `switch_to_next_column` does what you need.

Kind regards,
Joris Schellekens

**Comment by avi-chandra** [comment]
hey, sorry my bad I got confused and missed the Stackoverflow part. I will take care of this in future.

Thanks for your help.
