### ISSUE TITLE
feasibility question of generating annotated pdf files

### ISSUE THREAD

**Issue by christianmalek** [jorisschellekens/borb-examples#40]
Hello,

I would like to create PDFs and remember directly where content is positioned in the PDF (via the bounding box). Therefore I would like to know if it is possible to retrieve the calculated bounding box of objects directly when creating PDFs with Borb. I assume that it should be possible somehow as soon as you add an element like a paragraph to a layout.

**Comment by jorisschellekens** [comment]
Please check out the code for `LayoutElement`.

You'll see it has a method `get_previous_paint_box()`

Also, please ask any questions you may have through StackOverflow. The issues here are meant for "there is something wrong with the examples" and not "I have a question about the library in general".

Kind regards,
Joris Schellekens
