### ISSUE TITLE
CSS doesn't apply when when create pdf from html.

### ISSUE THREAD

**Issue by umair313** [jorisschellekens/borb-examples#8]
I created some PDFs from HTML but styling did not apply. I tried in <style> tag and in inline style as well. both did work.

**Comment by jorisschellekens** [comment]
Hi,

As mentioned in the text of the "html to pdf" example, `borb` currently only supports basic html to pdf conversion.

Some things are not supported:
- javascript
- css
- some html tags

I explicitly mention to keep an eye out for this functionality in new releases, as it is likely to change (more features being added).

So, currently this is not a bug. It is a known limitation of the library.
